### ISSUE TITLE
readIntegrationResponse missing from python aws-apigateway-dynamodb

### ISSUE THREAD

**Issue by Gamecock** [awslabs/aws-solutions-constructs#897]
Cannot create an integration response with python CDK.

Documentation has:

|additionalReadRequestTemplates?|`{ [contentType: string]: string; }`|Optional Read Request Templates for content-types other than `application/json`. Use the `readRequestTemplate` property to set the request template for the `application/json` content-type.|
|readIntegrationResponses?|[`api.IntegrationResponses[]`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.IntegrationResponse.html)|Optional, custom API Gateway Integration Response for the read method.|

however it's missing from the __init.py__

 

> def __init__(
>         self,
>         scope: _constructs_77d1e7e8.Construct,
>         id: builtins.str,
>         *,
>         allow_create_operation: typing.Optional[builtins.bool] = None,
>         allow_delete_operation: typing.Optional[builtins.bool] = None,
>         allow_read_operation: typing.Optional[builtins.bool] = None,
>         allow_update_operation: typing.Optional[builtins.bool] = None,
>         api_gateway_props: typing.Optional[typing.Union[_aws_cdk_aws_apigateway_ceddda9d.RestApiProps, typing.Dict[builtins.str, typing.Any]]] = None,
>         create_request_template: typing.Optional[builtins.str] = None,
>         delete_request_template: typing.Optional[builtins.str] = None,
>         dynamo_table_props: typing.Optional[typing.Union[_aws_cdk_aws_dynamodb_ceddda9d.TableProps, typing.Dict[builtins.str, typing.Any]]] = None,
>         existing_table_obj: typing.Optional[_aws_cdk_aws_dynamodb_ceddda9d.Table] = None,
>         log_group_props: typing.Optional[typing.Union[_aws_cdk_aws_logs_ceddda9d.LogGroupProps, typing.Dict[builtins.str, typing.Any]]] = None,
>         read_request_template: typing.Optional[builtins.str] = None,
>         update_request_template: typing.Optional[builtins.str] = None,
>     ) -> None: 
> 
> 

### Reproduction Steps

```
from aws_solutions_constructs.aws_apigateway_dynamodb import ApiGatewayToDynamoDB
from aws_cdk import Stack,  aws_apigateway
from constructs import Construct

class ApiGatewayBugStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        ApiGatewayToDynamoDB(self, 'test-api-gateway-dynamodb-default',
                             read_integration_responses=[
                                aws_apigateway.IntegrationResponse(status_code="200")]
        )
```
then
`cdk synth`

### Error Log

Traceback (most recent call last):
  File "C:\Projects\AWS\API_GATEWAY_BUG\app.py", line 10, in <module>
    ApiGatewayBugStack(app, "ApiGatewayBugStack",
  File "C:\Projects\AWS\API_GATEWAY_BUG\.venv\lib\site-packages\jsii\_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Projects\AWS\API_GATEWAY_BUG\api_gateway_bug\api_gateway_bug_stack.py", line 10, in __init__
    ApiGatewayToDynamoDB(self, 'test-api-gateway-dynamodb-default',
  File "C:\Projects\AWS\API_GATEWAY_BUG\.venv\lib\site-packages\jsii\_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: ApiGatewayToDynamoDB.__init__() got an unexpected keyword argument 'read_integration_responses'

### Environment

  - **CDK CLI Version  **  2.63.0 (build 7f4e35e)
  - **CDK Framework Version:  **  
  - **AWS Solutions Constructs Version     :** 2.30.0
  - **OS                   :**   Windows
  - **Language             :**  Pything

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks - we'll take a look.

**Comment by biffgaut** [comment]
First question as we start looking - 

The additionalReadRequestTemplates feature was added in v2.31.0, but you list 2.30.0 as your Constructs version. If you upgrade to 2.31.0 does it address your issue?

(PRs get pushed to main but don't get to pypi, npm, Maven, etc. until we push a new release. 2.31.0 was pushed yesterday afternoon).

**Comment by Gamecock** [comment]
Yes, working in v2.31.0 talk about JIT release :)
